### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Axkaban** [KellyDesigns/prj-rev-bwfs-dasmoto#2]
Nice implementation of classes: 
[https://github.com/KellyDesigns/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/idex.html#L19](https://github.com/KellyDesigns/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/idex.html#L19)
 and the span tags:
[https://github.com/KellyDesigns/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/idex.html#L23](uhttps://github.com/KellyDesigns/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/idex.html#L23)

What I will like to mention is that you may want to start implementing comments to specify each section of the page, for now it is a very simple page but as you progress, you will notice that your html file will be more complex and comments will help you identify or find elements more efficiently. Something basic like: `<!-- Brushes section-->` will suffice.

**Comment by KellyDesigns** [comment]
Thank You! I will take your advice and start using comments.
