### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Axkaban** [KellyDesigns/prj-rev-bwfs-dasmoto#3]
Great!
Very good implementation of the `html` selector here: [https://github.com/KellyDesigns/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L1](https://github.com/KellyDesigns/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L1)

You could've use the `*` (all ) selector but its downfall is that overwrites other elements with whatever property that both share, yet it will always have a place in specific circumstances. Other option very common is just pass universal styles through a `body` selector, if all the elements that you want to affect are children of the body element.

Also, good work selecting a specific child of an element like here:
[https://github.com/KellyDesigns/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L19](https://github.com/KellyDesigns/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L19)

**Comment by KellyDesigns** [comment]
Thanks!
